name: CI/CD for Email Assistant

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from GitHub
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Or any version you prefer

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: |
          . .venv/bin/activate
          pytest tests  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      # Step 1: Checkout code again
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      # Step 3: Deploy the app (example for Heroku)
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Store Heroku API key as a GitHub secret
        run: |
          git remote add heroku https://git.heroku.com/your-app-name.git
          git push heroku main
